import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ConditionalNavbar from "./components/ConditionalNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Sisphus Apply",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
        lang="en"
        className={`${lato.variable} h-full antialiased`}
      >
        <body className="min-h-full bg-(--stone) flex flex-col font-(--font-lato) text-(--rock)" suppressHydrationWarning>
          <ConditionalNavbar>
            <Navbar />
          </ConditionalNavbar>
          {children}
        </body>
      </html>
  );
}
