import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import UserMenu from "./components/UserMenu";
import { SessionProvider } from "next-auth/react";


const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Sisphus Apply",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html
        lang="en"
        className={`${lato.variable} h-full antialiased`}
      >
        <body className="min-h-full bg-(--stone) flex flex-col font-(--font-lato) text-(--rock)" suppressHydrationWarning>
          <SessionProvider>
            <div className="z-1 relative">
              <Navbar />
            </div>
            {children}
          </SessionProvider>
          
        </body>
      </html>
  );
}
